### PR TITLE
task: Rename Program to app

### PR DESCRIPTION
**Pull request by marsicdev**

### CODE REVIEW

**Review by Jeckaa — CHANGES_REQUESTED** [review]
Change "Hi from App!" to "Hi from App"

**Review by magdalena997 — DISMISSED** [review]

**Comment by marsicdev** [comment]
@Jeckaa this is fixed, ready for review

**Review by Jeckaa — APPROVED** [review]
LGTM

**Review by magdalena997 — APPROVED** [review]
LGTM

**Pull request merged**
